version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    parallelism: 4
    steps:
      - checkout
      - run: npm install
      - run: npm test

workflows:
  my_workflow:
    jobs:
      - build